"""Bounded delivery for events received by public tracking endpoints."""

from __future__ import annotations

import asyncio
import logging
import re
import time
from collections import deque
from dataclasses import dataclass
from typing import Awaitable, Callable

import httpx


logger = logging.getLogger(__name__)

TRACKING_ID_PATTERN = re.compile(r"^[A-Za-z0-9_-]{8,128}$")
TRACKING_ENDPOINTS = {
    "/api/tracking/email-opened",
    "/api/tracking/link-clicked",
}


def is_valid_tracking_id(value: str) -> bool:
    return bool(TRACKING_ID_PATTERN.fullmatch(value or ""))


@dataclass(frozen=True)
class TrackingEvent:
    endpoint: str
    tracking_id: str
    ip_address: str
    user_agent: str | None

    def __post_init__(self) -> None:
        if self.endpoint not in TRACKING_ENDPOINTS:
            raise ValueError("Unsupported tracking endpoint")
        if not is_valid_tracking_id(self.tracking_id):
            raise ValueError("Invalid tracking ID")


class TrackingRateLimiter:
    """Bound the database and queue work generated by public clients."""

    def __init__(
        self,
        *,
        window_seconds: int,
        max_per_client: int,
        max_global: int,
        clock: Callable[[], float] = time.monotonic,
    ) -> None:
        if min(window_seconds, max_per_client, max_global) <= 0:
            raise ValueError("Tracking rate limits must be positive")
        self.window_seconds = window_seconds
        self.max_per_client = max_per_client
        self.max_global = max_global
        self._clock = clock
        self._global_attempts: deque[float] = deque()
        self._client_attempts: dict[str, deque[float]] = {}
        self._lock = asyncio.Lock()

    @staticmethod
    def _prune(attempts: deque[float], cutoff: float) -> None:
        while attempts and attempts[0] <= cutoff:
            attempts.popleft()

    async def allow(self, client_key: str) -> bool:
        now = self._clock()
        cutoff = now - self.window_seconds
        key = client_key or "unknown"

        async with self._lock:
            self._prune(self._global_attempts, cutoff)
            if len(self._global_attempts) >= self.max_global:
                return False

            attempts = self._client_attempts.get(key)
            if attempts is None:
                attempts = deque()
                self._client_attempts[key] = attempts
            self._prune(attempts, cutoff)
            if len(attempts) >= self.max_per_client:
                return False

            self._global_attempts.append(now)
            attempts.append(now)

            # The global limit also bounds the number of live client keys.
            if len(self._client_attempts) > self.max_global:
                self._client_attempts = {
                    client: values
                    for client, values in self._client_attempts.items()
                    if values and values[-1] > cutoff
                }
            return True


class TrackingEventDispatcher:
    """Deliver events through a fixed worker pool and bounded queue."""

    def __init__(
        self,
        *,
        admin_api_url: str,
        internal_api_key: str,
        campaign_id: str,
        queue_size: int,
        worker_count: int,
        sender: Callable[[TrackingEvent], Awaitable[None]] | None = None,
    ) -> None:
        if queue_size <= 0 or worker_count <= 0:
            raise ValueError("Tracking dispatcher limits must be positive")
        self.admin_api_url = admin_api_url.rstrip("/")
        self.internal_api_key = internal_api_key
        self.campaign_id = campaign_id
        self.worker_count = worker_count
        self._queue: asyncio.Queue[TrackingEvent] = asyncio.Queue(
            maxsize=queue_size
        )
        self._sender = sender
        self._client: httpx.AsyncClient | None = None
        self._workers: list[asyncio.Task] = []

    @property
    def queue_size(self) -> int:
        return self._queue.qsize()

    @property
    def running(self) -> bool:
        return bool(self._workers)

    async def start(self) -> None:
        if self.running:
            return
        if self._sender is None:
            self._client = httpx.AsyncClient(timeout=5.0)
        self._workers = [
            asyncio.create_task(
                self._worker(),
                name=f"tracking-worker-{index}",
            )
            for index in range(self.worker_count)
        ]

    async def stop(self) -> None:
        if not self.running:
            return
        try:
            await asyncio.wait_for(self._queue.join(), timeout=5.0)
        except asyncio.TimeoutError:
            logger.warning(
                "Tracking dispatcher stopped with %d queued events",
                self._queue.qsize(),
            )
        finally:
            for worker in self._workers:
                worker.cancel()
            await asyncio.gather(*self._workers, return_exceptions=True)
            self._workers = []
            if self._client is not None:
                await self._client.aclose()
                self._client = None

    def enqueue(self, event: TrackingEvent) -> bool:
        try:
            self._queue.put_nowait(event)
            return True
        except asyncio.QueueFull:
            logger.warning("Tracking event queue is full; event dropped")
            return False

    async def _send(self, event: TrackingEvent) -> None:
        if self._sender is not None:
            await self._sender(event)
            return
        if self._client is None:
            raise RuntimeError("Tracking dispatcher is not running")

        response = await self._client.post(
            f"{self.admin_api_url}{event.endpoint}",
            headers={"X-Internal-API-Key": self.internal_api_key},
            json={
                "tracking_id": event.tracking_id,
                "campaign_id": self.campaign_id,
                "ip_address": event.ip_address,
                "user_agent": event.user_agent,
            },
        )
        response.raise_for_status()

    async def _worker(self) -> None:
        while True:
            event = await self._queue.get()
            try:
                await self._send(event)
            except asyncio.CancelledError:
                raise
            except httpx.TimeoutException:
                logger.warning("Tracking event delivery timed out")
            except httpx.HTTPError as exc:
                logger.warning("Tracking event delivery failed: %s", exc)
            except Exception:
                logger.exception("Unexpected tracking event delivery failure")
            finally:
                self._queue.task_done()
