http_port 3128

acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

acl private_dst dst 0.0.0.0/8
acl private_dst dst 10.0.0.0/8
acl private_dst dst 100.64.0.0/10
acl private_dst dst 127.0.0.0/8
acl private_dst dst 169.254.0.0/16
acl private_dst dst 172.16.0.0/12
acl private_dst dst 192.168.0.0/16
acl private_dst dst 224.0.0.0/4
acl private_dst dst 240.0.0.0/4
acl private_dst dst ::1/128
acl private_dst dst fc00::/7
acl private_dst dst fe80::/10

http_access deny private_dst
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow all
http_access deny all

request_header_access Proxy-Authorization deny all
request_header_access X-Forwarded-For deny all
request_header_access Via deny all
forwarded_for delete
via off
cache deny all
access_log none
cache_log /var/spool/squid/cache.log
coredump_dir /var/spool/squid
