certificatesResolvers:
  letsencrypt:
    acme:
      # Replaced from config.yaml by `p-bitm.py setup`.
      email: "admin@example.com"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        # Replaced from config.yaml by `p-bitm.py setup`.
        provider: duckdns
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          permanent: true
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: false

log:
  level: INFO

ping: {}

providers:
  docker:
    network: "server_bitm-network"
    exposedByDefault: false
    watch: true
    endpoint: "tcp://traefik-docker-proxy:2375"
